dist: trusty
sudo: required
language: bash

env:
  global:
    - tf_ver: 0.11.10
    - tf_zip: terraform_${tf_ver}_linux_amd64.zip

before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
    bash

install:
  - pip install --user -r ansible/requirements.txt
  - curl -O  https://releases.hashicorp.com/terraform/$tf_ver/$tf_zip
  - sudo unzip $tf_zip -d /usr/local/bin
  - curl -L -O https://github.com/wata727/tflint/releases/download/v0.7.2/tflint_linux_amd64.zip
  - sudo unzip tflint_linux_amd64.zip -d /usr/local/bin

script:
  # Packer validate
  - |
    for img in app db
    do
      packer validate --var-file packer/variables.json.example packer/${img}.json
    done

  # Terraform validate
  - cd terraform
  - |
    for env in stage prod
    do
      cd $env
      terraform init -backend=false
      terraform validate -check-variables=false
      cd ..
    done

  # Terraform tflint
  - |
    for env in stage prod
    do
      cd $env
      tflint
      cd ..
    done

  # Ansible syntax check
  - cd ../ansible
  - mkdir -p ~/.ansible && echo "test-password" > ~/.ansible/vault.key
  - ansible-playbook playbooks/site.yml --syntax-check

  # Ansible lint
  - ansible-lint playbooks/*.yml  --exclude=roles/jdauphant.nginx


notifications:
  slack:
    rooms:
      secure: h+UjzDNvyCeck7sW6+wBGUgCz5SPBQTFhMtNDFJMoxQnPqxZ6k5NFhjHa50IBFsoydZWU8qyF/AvypNcSfkGX4yA5K+KePY5htq4iR3Q5/bTtQF6VcnTa1S6ufDweBUVkzuUu9Mq47hYWjsoEtRmwkrv7XGQYUIdAyo3u2twq6D8WUry9sGNOndicxfwq+QxJr4OXsNij2eBgzSx1phRwUgH4iTpVvcxHwzdePNP0PrhlB4FP1dG+OrtzYsWDYZK1/aRkk9wdsW+6wqmQ2NHrlq8Cg9FuHtW99iabdm2wwDlP0cuXORYgJBbpOPx4pNMdxwo9mpXt5TYnvFCuWqqB+xxiUc1ZdZeMizX4Jkbgwqfiz8VHGmvwyqQTPjkX1tpIqf6k1GWh84dGS2gNsfFSTg88Qq7U6S/5q1NEf8gCVBNeAHyo1GL28g0YP6K+j2TKBwx186jC+3eo2fVGhWnTcnk2hFGTjDP0rw8YLFVPvN0oSjU3NqFA9tqFsSz7XkFhQ9TWNIPIZn5STl44ijNYLk3yvz8/ZbLpDLH8yMBBtQO/pMVOdiLXnp6zdEx3WFfyEiU+sMq2NvmPM9JWnKdmO7lVT+xnFXwRko6alq1q6oqq47WRwUlq9pefKJ3n1jeXn7rQHWKL2nujmbffKpLFzEGYRkQrazFtwFOJ6PMakY=
