---
- name: Configure application
  hosts: app
  gather_facts: no
  become: true
  vars:
    db_node_name: "{{ lookup('env', 'DB_NODE_NAME') }}"
    db_host: "{{ hostvars[ db_node_name ]['internal_ip'] }}"
  tasks:
    - name: Debug output
      debug: var=db_node_name

    - name: Check environment variable DB_NODE_NAME
      fail: msg="Environment variable DB_NODE_NAME must be defined"
      when: db_node_name == ''

    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config file for DB connection
      template: 
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: enable Puma
      systemd: name=puma enabled=yes
      
  handlers:
  - name: reload puma
    systemd: name=puma state=restarted

